import type { NextPage } from 'next';
import Head from 'next/head';
import { SideMenu } from '../components/SideMenu';
import styles from '../styles/Common.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.mainGrid}>
        <aside className={styles.aside}>
          <SideMenu />
        </aside>
        <main className={styles.main}>
          <h1>Home page</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis quibusdam eius doloribus aspernatur rerum.
          </p>
          <p>
            Nulla nihil, obcaecati adipisci illo, molestiae earum, veritatis soluta ipsum porro repellendus! Recusandae
            facere esse alias!
          </p>
        </main>
      </section>
    </div>
  );
};

export default Home;
